#  server:
#    port: 8081
#    address: 0.0.0.0
#
#  spring:
#    application:
#      name: user-service
#    datasource:
#      url: jdbc:mysql://mysql-db:3306/user_ServiceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
##      url: jdbc:mysql://localhost:3306/user_ServiceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: password
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect
#    jwt:
#      secret: your_secret_key_change_this_your_secret_key_change_this
#      expiration-ms: 86400000  # 24 hours
#
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"           # Expose all actuator endpoints
#    endpoint:
#      health:
#        show-details: always     # Show full health info (DB, disk, etc.)
#
#  eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
##        defaultZone: http://localhost:8761/eureka/
#        defaultZone: http://eureka-registry:8761/eureka/
#
#

server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: user-service
#  datasource:
##    url: jdbc:mysql://host.docker.internal:3306/user_ServiceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/user_ServiceDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: your_secret_key_change_this_your_secret_key_change_this
    expiration-ms: 86400000  # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: "*"           # Expose all actuator endpoints
    health:
      show-details: always     # Show full health info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://eureka:8761/eureka/
#       defaultZone: http://localhost:8761/eureka/
